source:
  type: local
  path: /home/ytm/test
dest:
  type: smb
  host: wfs-medizin.top.gwdg.de
  port: 445
  path: ukln100
  share-name: ukln-all$
  identity-file: /home/ytm/test/id-rsa
  username: yi1
  password: 1234567
  domain: gwdg
dustbin: /home/ytm/test2
execution:
  start-level: 2
  overwrite: true
  gid: 0
  uid: 0
known-hosts: "/home/ytm/.ssh/known_hosts"
