source:
  root-dir: /home/ytm/test
  start-level: 2
  overwrite: true
dest:
  host: transfer-mdc.hpc.gwdg.de
  port: 22
  identity-file: /home/ytm/test/id-rsa
  username: yi1
  path: /usr/yi1
  gid: 0
  uid: 0
dustbin: /home/ytm/test2
known-hosts: "/home/ytm/.ssh/known_hosts"
